stages:
  - build
  - deploy

build_job:
  stage: build
  image: node:latest
  script:
    - npm install
    - npx gulp gitLabBuild
  artifacts:
    paths:
      - release/plaza-core

deploy_job_main:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache lftp
  script:
    - lftp -c "set ftp:ssl-allow no; open -u $MAIN_FTP_USERNAME,$MAIN_FTP_PASSWORD $MAIN_FTP_HOST; mirror -Rnev ./release/plaza-core ./path/on/main/server --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
  only:
    - main

deploy_job_develop:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache lftp
  script:
    - lftp -c "set ftp:ssl-allow no; open -u $DEVELOP_FTP_USERNAME,$DEVELOP_FTP_PASSWORD $DEVELOP_FTP_HOST; mirror -Rnev ./release/plaza-core ./path/on/develop/server --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
  only:
    - develop
